version: "3"
services:
  signal:
    #env_file:
    #  - .web.env
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - .:/usr/src
    #depends_on:
    #links:
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      SECRET_KEY: $SECRET_KEY
